AllCops:
  Include:
    - "**/*.rb"
    - "config.ru"
    - "Rakefile"
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "data/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "lib/active_support/*.rb"
    - "node_modules/**/*"
  DisplayCopNames: true

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/LineLength:
  Max: 130

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundOperators:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 100
  Exclude:
    - "**/*.rake"
    - "spec/**/*"

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Exclude:
    - "**/*.rake"
    - "spec/**/*"

Naming/MethodParameterName:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Style/DateTime:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/FrozenStringLiteralComment:
  Enabled: false
